/**
 * GENERATED by tools/people-calibrate.ts + tools/people-measured.ts (M15 phase 32c) — do not edit by hand.
 * Variants lean, craft, leankit; seeds alpha, beta, gamma; one comarca each (the island of the scenario).
 * Regenerate: npx vite-node tools/people-calibrate.ts -- lean,craft,leankit alpha,beta,gamma <dir>/cal-<variant>.json (one per variant), then
 *             npx vite-node tools/people-measured.ts -- <dir> src/sim/world/PeopleMeasured.ts
 */

/** One season of one variant: adult supply ratio, and the share of hungry days with no relief. */
export interface CapacityPoint {
  readonly variant: string; readonly season: string;
  /** Rations fed per calendar day over the mean population: the quantity a region and a population give (see PeopleCapacity). */
  readonly s: number;
  /** Adult nominal nutrition eaten over hunger drift. Kept for reference; NOT the x axis (a first version used it, and the model's supply ratio is not it). */
  readonly adultS: number;
  /** Share of adult days that began hungry (need >= 25) and brought no relief at all. */
  readonly hungryZero: number;
  /** Share of adult days that began hungry. */
  readonly hungryShare: number;
  readonly hungryDays: number;
}
export const MEASURED_CAPACITY_POINTS: readonly CapacityPoint[] = [{"variant":"lean","season":"spring","s":0.446,"adultS":0.564,"hungryZero":0.756,"hungryShare":0.493,"hungryDays":275},{"variant":"lean","season":"summer","s":0.855,"adultS":0.97,"hungryZero":0.431,"hungryShare":0.574,"hungryDays":459},{"variant":"lean","season":"autumn","s":1.011,"adultS":1.206,"hungryZero":0.232,"hungryShare":0.448,"hungryDays":302},{"variant":"lean","season":"winter","s":0.396,"adultS":0.483,"hungryZero":0.808,"hungryShare":0.677,"hungryDays":401},{"variant":"craft","season":"spring","s":0.918,"adultS":1.144,"hungryZero":0.25,"hungryShare":0.32,"hungryDays":264},{"variant":"craft","season":"summer","s":1.073,"adultS":1.323,"hungryZero":0.153,"hungryShare":0.297,"hungryDays":327},{"variant":"craft","season":"autumn","s":0.999,"adultS":1.33,"hungryZero":0.121,"hungryShare":0.254,"hungryDays":280},{"variant":"craft","season":"winter","s":0.994,"adultS":1.261,"hungryZero":0.149,"hungryShare":0.221,"hungryDays":134},{"variant":"leankit","season":"spring","s":0.474,"adultS":0.633,"hungryZero":0.702,"hungryShare":0.548,"hungryDays":413},{"variant":"leankit","season":"summer","s":0.843,"adultS":0.95,"hungryZero":0.448,"hungryShare":0.579,"hungryDays":524},{"variant":"leankit","season":"autumn","s":0.986,"adultS":1.19,"hungryZero":0.245,"hungryShare":0.415,"hungryDays":319},{"variant":"leankit","season":"winter","s":0.445,"adultS":0.575,"hungryZero":0.767,"hungryShare":0.62,"hungryDays":417}];

/** What each measured world's comarca fed, per season: rations (one person's daily need) per calendar day. */
export const MEASURED_REGIONS = {"lean":{"comarcas":1,"initialPopulation":36.666666666666664,"rationsPerDay":{"spring":5.31,"summer":11,"autumn":14.28,"winter":6.46},"meanPopulation":{"spring":11.91,"summer":12.86,"autumn":14.12,"winter":16.32},"calendarDays":{"spring":75,"summer":90,"autumn":75,"winter":60}},"craft":{"comarcas":1,"initialPopulation":24.666666666666668,"rationsPerDay":{"spring":26.71,"summer":31.74,"autumn":32.13,"winter":30.96},"meanPopulation":{"spring":29.11,"summer":29.58,"autumn":32.15,"winter":31.15},"calendarDays":{"spring":45,"summer":60,"autumn":60,"winter":33}},"leankit":{"comarcas":1,"initialPopulation":36.666666666666664,"rationsPerDay":{"spring":7.9,"summer":12.7,"autumn":16.77,"winter":8.94},"meanPopulation":{"spring":16.65,"summer":15.06,"autumn":17.01,"winter":20.08},"calendarDays":{"spring":75,"summer":90,"autumn":75,"winter":60}}} as const;

/** Whole-run totals per variant, for checking the model against what produced the curve. */
export const MEASURED_TOTALS = {"lean":{"starvationDeaths":86,"deaths":127,"personYears":102.7,"starvationPerPersonYear":0.837,"births":20,"womanYears":26.2,"birthsPerWomanYear":0.763},"craft":{"starvationDeaths":2,"deaths":4,"personYears":152,"starvationPerPersonYear":0.013,"births":38,"womanYears":39.8,"birthsPerWomanYear":0.954},"leankit":{"starvationDeaths":120,"deaths":135,"personYears":127.9,"starvationPerPersonYear":0.938,"births":30,"womanYears":32.1,"birthsPerWomanYear":0.935}} as const;

/**
 * Rations per day fed by the same world when the founders know the foraging kit (firemaking, plant_lore,
 * cooking), over the world that does not, weighted by days. Three seeds, and confounded: a bigger supply keeps
 * more people alive, which is what was measured (s barely moves, population does).
 */
export const MEASURED_KIT = { techs: ['firemaking', 'plant_lore', 'cooking'], multiplier: 1.24 } as const;
