/**
 * Folds the outputs of tools/people-calibrate.ts into src/sim/world/PeopleMeasured.ts (M15 phase 32c).
 *
 *   npx vite-node tools/people-measured.ts -- <dir with cal-lean.json cal-craft.json cal-leankit.json> <out.ts>
 */
import { readFileSync, writeFileSync } from 'node:fs';
const args = process.argv.slice(2).filter(a => a !== '--');
const dir = args[0]!, out = args[1]!;
const SEASONS = ['spring', 'summer', 'autumn', 'winter'];
const read = (v: string) => JSON.parse(readFileSync(`${dir}/cal-${v}.json`, 'utf8')).result[v];
const data = { lean: read('lean'), craft: read('craft'), leankit: read('leankit') } as Record<string, any>;

const points: unknown[] = [];
const regions: Record<string, unknown> = {};
const totals: Record<string, unknown> = {};
for (const v of Object.keys(data)) {
  const d = data[v];
  for (const s of SEASONS) {
    const r = d.seasons[s];
    points.push({ variant: v, season: s, s: Number((r.rationsPerDay / r.meanPopulation).toFixed(3)), adultS: r.adultSupplyRatio, hungryZero: r.hungryZero, hungryShare: r.hungryShare, hungryDays: r.hungryDays });
  }
  regions[v] = {
    comarcas: 1, initialPopulation: d.initialPopulation,
    rationsPerDay: Object.fromEntries(SEASONS.map(s => [s, d.seasons[s].rationsPerDay])),
    meanPopulation: Object.fromEntries(SEASONS.map(s => [s, d.seasons[s].meanPopulation])),
    calendarDays: Object.fromEntries(SEASONS.map(s => [s, d.seasons[s].calendarDays])),
  };
  totals[v] = {
    starvationDeaths: d.starvationDeaths, deaths: d.deaths, personYears: d.personYears,
    starvationPerPersonYear: d.starvationPerPersonYear, births: d.births, womanYears: d.womanYears,
    birthsPerWomanYear: d.birthsPerWomanYear,
  };
}
const dayWeighted = (v: string) => SEASONS.reduce((n, s) => n + data[v].seasons[s].rationsPerDay * data[v].seasons[s].calendarDays, 0)
  / SEASONS.reduce((n, s) => n + data[v].seasons[s].calendarDays, 0);
const kitMultiplier = Number((dayWeighted('leankit') / dayWeighted('lean')).toFixed(3));

writeFileSync(out, `/**
 * GENERATED by tools/people-calibrate.ts + tools/people-measured.ts (M15 phase 32c) — do not edit by hand.
 * Variants lean, craft, leankit; seeds ${data.lean.seeds.join(', ')}; one comarca each (the island of the scenario).
 * Regenerate: npx vite-node tools/people-calibrate.ts -- lean,craft,leankit alpha,beta,gamma <dir>/cal-<variant>.json (one per variant), then
 *             npx vite-node tools/people-measured.ts -- <dir> src/sim/world/PeopleMeasured.ts
 */

/** One season of one variant: adult supply ratio, and the share of hungry days with no relief. */
export interface CapacityPoint {
  readonly variant: string; readonly season: string;
  /** Rations fed per calendar day over the mean population: the quantity a region and a population give (see PeopleCapacity). */
  readonly s: number;
  /** Adult nominal nutrition eaten over hunger drift. Kept for reference; NOT the x axis (a first version used it, and the model's supply ratio is not it). */
  readonly adultS: number;
  /** Share of adult days that began hungry (need >= 25) and brought no relief at all. */
  readonly hungryZero: number;
  /** Share of adult days that began hungry. */
  readonly hungryShare: number;
  readonly hungryDays: number;
}
export const MEASURED_CAPACITY_POINTS: readonly CapacityPoint[] = ${JSON.stringify(points)};

/** What each measured world's comarca fed, per season: rations (one person's daily need) per calendar day. */
export const MEASURED_REGIONS = ${JSON.stringify(regions)} as const;

/** Whole-run totals per variant, for checking the model against what produced the curve. */
export const MEASURED_TOTALS = ${JSON.stringify(totals)} as const;

/**
 * Rations per day fed by the same world when the founders know the foraging kit (firemaking, plant_lore,
 * cooking), over the world that does not, weighted by days. Three seeds, and confounded: a bigger supply keeps
 * more people alive, which is what was measured (s barely moves, population does).
 */
export const MEASURED_KIT = { techs: ['firemaking', 'plant_lore', 'cooking'], multiplier: ${kitMultiplier} } as const;
`);
console.log('wrote ' + out + ' kit multiplier ' + kitMultiplier);
